











[34m[1mwandb[39m[22m: wandb version 0.16.0 is available!  To upgrade, please run:
[34m[1mwandb[39m[22m:  $ pip install wandb --upgrade
[34m[1mwandb[39m[22m: Tracking run with wandb version 0.15.4
[34m[1mwandb[39m[22m: Run data is saved locally in [35m[1m/Users/sach/Development/Python/VANO/wandb/run-20231205_143934-a0zawi9d
[34m[1mwandb[39m[22m: Run [1m`wandb offline`[22m to turn off syncing.
[34m[1mwandb[39m[22m: Syncing run [33mnerf
[34m[1mwandb[39m[22m: ‚≠êÔ∏è View project at [34m[4mhttps://wandb.ai/slewin/vano
[34m[1mwandb[39m[22m: üöÄ View run at [34m[4mhttps://wandb.ai/slewin/vano/runs/a0zawi9d














[34m[1mwandb[39m[22m: | Waiting for wandb.init()...
Exception in callback future.<locals>.callback(<Task cancell...ulers.py:149>>) at /Users/sach/miniconda3/envs/deeplearning/lib/python3.9/site-packages/dawgz/utils.py:77
handle: <Handle future.<locals>.callback(<Task cancell...ulers.py:149>>) at /Users/sach/miniconda3/envs/deeplearning/lib/python3.9/site-packages/dawgz/utils.py:77>
Traceback (most recent call last):
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/asyncio/base_events.py", line 1869, in _run_once
    event_list = self._selector.select(timeout)
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/site-packages/dawgz/schedulers.py", line 158, in _submit
    return await self.exec(job)
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/site-packages/dawgz/schedulers.py", line 260, in exec
    results = await asyncio.gather(*map(call, job.array), return_exceptions=True)
asyncio.exceptions.CancelledError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/site-packages/dawgz/utils.py", line 78, in callback
    result = self.exception()
asyncio.exceptions.CancelledError
Traceback (most recent call last):
  File "/Users/sach/Development/Python/VANO/experiments/2d_gaussian_pdf.py", line 499, in <module>
    print(f"Launching {len(train.array)} jobs with backend {backend}")
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/site-packages/dawgz/schedulers.py", line 192, in schedule
    scheduler.wait(*jobs)
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/site-packages/dawgz/schedulers.py", line 128, in wait
    asyncio.run(self._wait(*jobs))
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/asyncio/base_events.py", line 1869, in _run_once
    event_list = self._selector.select(timeout)
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/sach/Development/Python/VANO/experiments/2d_gaussian_pdf.py", line 499, in <module>
    print(f"Launching {len(train.array)} jobs with backend {backend}")
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/site-packages/dawgz/schedulers.py", line 192, in schedule
    scheduler.wait(*jobs)
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/site-packages/dawgz/schedulers.py", line 128, in wait
    asyncio.run(self._wait(*jobs))
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/asyncio/base_events.py", line 1869, in _run_once
    event_list = self._selector.select(timeout)
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/sach/Development/Python/VANO/experiments/2d_gaussian_pdf.py", line 499, in <module>
    print(f"Launching {len(train.array)} jobs with backend {backend}")
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/site-packages/dawgz/schedulers.py", line 192, in schedule
    scheduler.wait(*jobs)
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/site-packages/dawgz/schedulers.py", line 128, in wait
    asyncio.run(self._wait(*jobs))
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/asyncio/base_events.py", line 1869, in _run_once
    event_list = self._selector.select(timeout)
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/sach/Development/Python/VANO/experiments/2d_gaussian_pdf.py", line 499, in <module>
    print(f"Launching {len(train.array)} jobs with backend {backend}")
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/site-packages/dawgz/schedulers.py", line 192, in schedule
    scheduler.wait(*jobs)
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/site-packages/dawgz/schedulers.py", line 128, in wait
    asyncio.run(self._wait(*jobs))
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/asyncio/base_events.py", line 1869, in _run_once
    event_list = self._selector.select(timeout)
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt
Exception ignored in: <module 'threading' from '/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/threading.py'>
Traceback (most recent call last):
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/threading.py", line 1447, in _shutdown
    atexit_call()
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/concurrent/futures/thread.py", line 31, in _python_exit
    t.join()
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/threading.py", line 1060, in join
    self._wait_for_tstate_lock()
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/threading.py", line 1080, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
KeyboardInterrupt:
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/site-packages/wandb/sdk/wandb_manager.py", line 186, in _teardown
    result = self._service.join()
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/site-packages/wandb/sdk/service/service.py", line 216, in join
    ret = self._internal_proc.wait()
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/subprocess.py", line 1189, in wait
    return self._wait(timeout=timeout)
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/subprocess.py", line 1933, in _wait
    (pid, sts) = self._try_wait(0)
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/subprocess.py", line 1891, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/subprocess.py", line 1189, in wait
    return self._wait(timeout=timeout)
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/subprocess.py", line 1933, in _wait
    (pid, sts) = self._try_wait(0)
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/subprocess.py", line 1891, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/site-packages/wandb/sdk/wandb_manager.py", line 186, in _teardown
    result = self._service.join()
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/site-packages/wandb/sdk/service/service.py", line 216, in join
    ret = self._internal_proc.wait()
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/subprocess.py", line 1202, in wait
    self._wait(timeout=sigint_timeout)
  File "/Users/sach/miniconda3/envs/deeplearning/lib/python3.9/subprocess.py", line 1927, in _wait
    time.sleep(delay)
KeyboardInterrupt